### PR TITLE
Bring sensor configs up to date with current versions

### PR DESCRIPTION
**Pull request by whartond**
Update configs for the latest sensor versions.

Change the Suricata ruleset that gets downloaded if there are no rules to be more current and compatible with the latest supported versions of Suricata.

### CODE REVIEW

**Comment by whartond** [comment]
FYI @rkoumis

**Comment by rkoumis** [comment]
Should this file `suricata-7.0.0.yaml` be in the directory `./app/static/engine-configs/suricata/` ?

**Comment by whartond** [comment]
> Should this file `suricata-7.0.0.yaml` be in the directory `./app/static/engine-configs/suricata/` ?

Yes. My mistake.

**Comment by rkoumis** [comment]
I tried running a random pcap through suricata with the default rules and got an error. Here are the logs:
```
*****
Aug 14 2024 17:44:08
*****
Agent Name: 6488bb832fe2
Agent Version: 3.1.1
IDS Engine: suricata 7.0.6
Dalton API: http://dalton_web/dalton/sensor_api
*****
submit_job() called
*****
manifest.json: [{'id': '93ea1a7fc9ecc225', 'pcaps': ['0343feb8a2ff7eb.pcap'], 'engine-conf': '94ab79a6e1158597_suricata.yaml', 'user': 'undefined', 'enable-all-rules': False, 'show-flowbit-alerts': False, 'custom-rules': False, 'track-performance': False, 'get-engine-stats': False, 'teapot-job': False, 'split-pcaps': False, 'use-suricatasc': True, 'alert-detailed': False, 'get-fast-pattern': False, 'get-other-logs': True, 'get-buffer-dumps': False, 'sensor-tech': 'suricata/7.0.6', 'prod-ruleset': 'ET-20240801-all-suricata.rules', 'override-external-net': True, 'suricata-eve': True, 'zeek-json-logs': False}]
*****
adding default-rule-path to yaml:
/tmp/93ea1a7fc9ecc225_Aug-14-2024_17-44-08/ET-20240801-all-suricata.rules
*****
Using Suricata Socket Control ... run_suricata_sc() called
*****
Running pcap(s) thru Suricata; using socket control
*****
Starting suricata thread with the following command:
suricata -c /tmp/93ea1a7fc9ecc225_Aug-14-2024_17-44-08/94ab79a6e1158597_suricata.yaml -k none --runmode single --unix-socket=/opt/dalton-agent/dalton-agent.socket -D
*****
ERROR!
*****
ERROR:
Problem starting Suricata daemon: [24 - Suricata-Main] 2024-08-14 17:44:09 Error: detect-pcre: Expression seen with a sticky buffer still set; either (1) reset sticky buffer with pkt_data or (2) use a sticky buffer providing "http request uri".

*****
Total Processing Time (includes job download time): 2 seconds
*****
send_results() called
*****
Sending back results
```

**Comment by rkoumis** [comment]
Additional logs:
```
[17 - Suricata-Main] 2024-08-14 17:43:19 Notice: suricata: This is Suricata version 7.0.6 RELEASE running in SYSTEM mode
[17 - Suricata-Main] 2024-08-14 17:43:19 Info: cpu: CPUs/cores online: 12
[17 - Suricata-Main] 2024-08-14 17:43:19 Info: suricata: Setting engine mode to IDS mode by default
[17 - Suricata-Main] 2024-08-14 17:43:19 Info: exception-policy: master exception-policy set to: auto
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: fast output device (regular) initialized: dalton-fast.log
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: eve-log output device (regular) initialized: dalton-eve.json
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: http-log output device (regular) initialized: dalton-http.log
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: tls-log output device (regular) initialized: dalton-tls.log
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: alert-debug output device (regular) initialized: dalton-alert_debug.log
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: logopenfile: stats output device (regular) initialized: dalton-stats.log
[18 - Suricata-Main] 2024-08-14 17:43:19 Info: counters: Alerts: 0
[18 - Suricata-Main] 2024-08-14 17:43:20 Error: detect-pcre: Expression seen with a sticky buffer still set; either (1) reset sticky buffer with pkt_data or (2) use a sticky buffer providing "http request uri".
[18 - Suricata-Main] 2024-08-14 17:43:20 Error: detect: error parsing signature "alert http $HOME_NET any -> $EXTERNAL_NET any (msg:"ET INFO TinyURL to Netlify Redirect"; flow:established,to_server; content:"GET"; http_method; content:"tinyurl.com"; http_host; content:".netlify.app/"; fast_pattern; http_referer; pcre:"/\.netlify\.app\x2f$/Ui"; classtype:bad-unknown; sid:2054423; rev:2; metadata:attack_target Client_Endpoint, created_at 2024_07_09, deployment Perimeter, confidence High, signature_severity Informational, updated_at 2024_07_22;)" from file /tmp/bcd51f4a179ba9f6_Aug-14-2024_17-43-19/ET-20240801-all-suricata.rules at line 18347
```

**Comment by rkoumis** [comment]
thanks for reminding me about the readme. Maybe update the readme for suricata version 6 ??

**Comment by whartond** [comment]
> I tried running a random pcap through suricata with the default rules and got an error. Here are the logs:

That's what https://github.com/secureworks/dalton/pull/174/commits/131f55ef66c33c35c3f40295b536f6853eaeca2c should fix.  But if you still had an old ruleset downloaded, it won't download the new one.  Try deleting the ruleset(s) from `rulesets/suricata/ET-*.rules` and restarting Dalton.  Then try your job again.

**Review by rkoumis — APPROVED** [review]
Looks great. Thank you.

**Pull request merged**
